#!/usr/bin/env zsh
pushd $DOTFILES

stow_folders=($(echo $STOW_FOLDERS | sed "s/,/ /g"))

echo $stow_folders

for folder in $stow_folders; do
    echo "Removing $folder"
    stow -D $folder
done
popd
